// This runner is auto-generated by Brittle

runTests()

async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./feature/auth-controller.test.js')
  await import('./unit/auth-controller.test.js')
  await import('./unit/auth-service.test.js')

  test.resume()
}
